'use strict';
const E=Werewolf,R=E.roles,app=document.getElementById('app'),SAVE='moon-werewolf-game-v1',PRESETS='moon-werewolf-presets-v1';
let game=null,screen='home',opened=false,publicOpened=false,selected=null,holdTimer=null,inactivity=null,saveError='',timerLoop=null,revealTimer=null,revealing=false;
let config={n:8,names:Array.from({length:8},(_,i)=>`参加者${i+1}`),counts:E.preset(8),kind:'basic',settings:{minutes:5,firstSeer:'free',repeatGuard:true,tie:'none',reveal:'none',showVotes:false}};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(a,t,cls='',disabled=false)=>`<button data-action="${a}" class="${cls}" ${disabled?'disabled':''}>${t}</button>`;
function getSaved(){try{return JSON.parse(localStorage.getItem(SAVE)||'null');}catch{return null;}}
function goodGame(g){return g&&g.version===1&&Array.isArray(g.players)&&g.players.length>=5&&g.players.length<=20&&g.players.every((p,i)=>p.id===i&&R[p.role]&&typeof p.alive==='boolean'&&Array.isArray(p.history))&&['deal','night','results','morning','day','vote','tie','exile','end'].includes(g.phase)&&g.settings&&Array.isArray(g.events);}
function store(){try{if(game&&game.phase!=='end')localStorage.setItem(SAVE,JSON.stringify(game));else localStorage.removeItem(SAVE);saveError='';}catch{saveError='このブラウザでは自動保存できません。画面を閉じずに遊んでください。';}}
function savedPresets(){try{let p=JSON.parse(localStorage.getItem(PRESETS)||'[]');return Array.isArray(p)?p:[];}catch{return [];}}
function resetPrivate(){PublicAudio.stop();opened=false;publicOpened=false;selected=null;clearTimeout(inactivity);clearTimeout(revealTimer);revealing=false;}
function canPlayPublicSound(){return screen==='game'&&game&&!opened&&['morning','tie','exile','end','day'].includes(game.phase)&&(revealing||publicOpened||game.phase==='end'||game.phase==='day');}
function audioControls(){return `<div class="audio-controls">${btn('toggle-audio',PublicAudio.enabled?'♪ 発表の効果音：オン':'♪ 発表の効果音：オフ','subtle')}<label>音量 <input data-volume type="range" min="5" max="50" value="${Math.round(PublicAudio.volume*100)}" aria-label="発表の効果音の音量"></label><span class="hint">個人の操作は常に無音</span></div>`;}
function go(){resetPrivate();store();render();window.scrollTo(0,0);}
function current(){return game.players[game.phase==='deal'?game.i:game.queue[game.i]];}
function roleList(c){return Object.keys(R).filter(k=>c[k]>0).map(k=>`${R[k].name} ${c[k]}人`).join(' ／ ');}
function home(){let saved=getSaved();app.innerHTML=`<section class="hero"><div><p class="eyebrow">A NIGHT IN THE VILLAGE</p><h1>この村に、<br>人狼がひそんでいる。</h1><p class="lead">話し合い、信じて、見抜く。<br>タブレットを順番に回して、みんなで人狼を遊ぼう。</p><div class="pills"><span class="pill">5〜20人</span><span class="pill">端末1台</span><span class="pill">司会役なし</span></div><div class="actions">${btn('setup','新しいゲーム','primary')}${saved?btn('resume','途中から再開','secondary'):''}${btn('rules','遊び方')}</div></div><div class="hero-art">${villageArt()}<span class="art-caption">月あかりに照らされた、小さな村。</span></div></section><section class="panel home-rules"><h2>人狼の遊び方</h2><div class="rule-steps"><div><span class="rule-number">01</span><h3>役職を確認</h3><p>端末を回して、自分の役職を秘密で確認します。</p></div><div><span class="rule-number">02</span><h3>昼は話し合いと投票</h3><p>誰が人狼かを推理し、投票で1人を追放します。</p></div><div><span class="rule-number">03</span><h3>夜は襲撃と能力</h3><p>人狼は襲撃先を、占い師や騎士は能力の対象を選びます。初日は襲撃なし。</p></div></div><div class="rule-victory"><p><strong>村人陣営の勝利</strong> 人狼を全員追放する。</p><p><strong>人狼陣営の勝利</strong> 生存する人狼が、それ以外の生存者と同数以上になる。</p></div><p class="hint">昼と夜を繰り返し、どちらかの陣営が勝つまで遊びます。</p></section>`;}
function setup(){let c=config.counts,total=Object.values(c).reduce((a,b)=>a+b,0),error=E.validate(c,config.n);let warnings=[];if(c.shared&&config.n<10)warnings.push('共有者は10人以上が目安です。村人陣営の情報が増えます。');if(c.fanatic&&config.n<8)warnings.push('狂信者は8人以上が目安です。人狼陣営の情報が増えます。');if(c.mad&&c.fanatic)warnings.push('狂人と狂信者の併用は、人狼陣営が強くなりやすい設定です。');if(c.shared&&c.fanatic)warnings.push('特殊役職は、まず1種類ずつ試すのがおすすめです。');
 const rows=special=>Object.entries(R).filter(([k,r])=>!!r.special===special).map(([k,r])=>`<div class="role-row"><span class="role-icon">${roleArt(k)}</span><div class="role-info"><strong>${r.name}</strong><small>${esc(r.desc)}</small></div><div class="stepper">${btn('minus:'+k,'−','',c[k]===0)}<output aria-label="${r.name}の人数">${c[k]}</output>${btn('plus:'+k,'＋','',c[k]>=20)}</div></div>`).join('');
 app.innerHTML=`<div class="topline"><p class="eyebrow">村の準備</p>${btn('home','ホーム','subtle')}</div><h1>誰と、どんな村で遊ぶ？</h1><div class="split"><section class="panel"><h2>参加者</h2><label>人数 <select id="number">${Array.from({length:16},(_,i)=>`<option value="${i+5}" ${config.n===i+5?'selected':''}>${i+5}人</option>`).join('')}</select></label><p class="hint">この順番で端末を回します。席順に名前を入れてください。</p><div class="names">${config.names.map((n,i)=>`<label><span>${i+1}</span><input type="text" data-name="${i}" aria-label="参加者${i+1}の名前" maxlength="20" value="${esc(n)}"></label>`).join('')}</div></section><section class="panel"><h2>役職を選ぶ</h2><label>おすすめ配役 <select id="kind">${[['beginner','はじめて（特殊役職なし）'],['basic','基本（特殊役職なし）'],['shared','共有者を追加'],['fanatic','狂信者を追加'],['custom','自由に調整']].map(([k,t])=>`<option value="${k}" ${config.kind===k?'selected':''}>${t}</option>`).join('')}</select></label><h3>基本役職</h3><div class="roles">${rows(false)}</div><h3>特殊役職 <span class="hint">お好みで追加</span></h3><div class="roles">${rows(true)}</div><p class="count">役職 ${total}人 ／ 参加者 ${config.n}人</p>${btn('fill','残りを村人で埋める','subtle')}</section></div><section class="panel"><details><summary>詳細ルールを調整する</summary><div class="settings">${setting('minutes','議論時間',[[1,'1分'],[3,'3分'],[5,'5分'],[7,'7分'],[10,'10分'],[15,'15分'],[0,'時間制限なし']])}${setting('firstSeer','初日の占い',[['free','自分で1人選ぶ'],['none','占いなし']])}${setting('repeatGuard','騎士の連続護衛',[[true,'同じ相手を続けて守れる'],[false,'同じ相手は続けて守れない']])}${setting('tie','再投票でも同票のとき',[['none','その日は追放なし'],['random','同票候補から抽選']])}${setting('reveal','脱落した人の役職',[['none','公開しない'],['exile','追放した人だけ公開'],['all','全員公開']])}${setting('showVotes','誰が誰に投票したか',[[false,'公開しない'],[true,'全員の投票後に公開']])}</div></details><p class="hint">初日は襲撃なし。騎士は自分を守れません。人狼は仲間の入力済みの襲撃先を見られます。</p>${warnings.map(w=>`<p class="notice">${w}</p>`).join('')}${error?`<p class="error" role="alert">${error}</p>`:''}<div class="actions">${btn('confirm','この設定で進む','primary',!!error)}${btn('save-preset','設定を保存')}${btn('load-preset','保存した設定')}</div></section>`;
}
function setting(key,label,choices){return `<label>${label}<select data-setting="${key}">${choices.map(([v,t])=>`<option value="${v}" ${String(config.settings[key])===String(v)?'selected':''}>${t}</option>`).join('')}</select></label>`;}
function confirmScreen(){app.innerHTML=`<p class="eyebrow">みんなで確認</p><h1>この村のルール</h1><section class="panel"><h2>${config.n}人の配役</h2><p class="lead">${roleList(config.counts)}</p><ul class="log"><li>村人陣営：人狼を全員追放すると勝利。</li><li>人狼陣営：生存人狼が、それ以外の生存者と同数以上になると勝利。</li><li>狂人・狂信者は人狼の味方ですが、人狼の人数には数えません。</li><li>初日は襲撃なし。占い：${{random:'ランダムの非人狼情報',free:'自由に選択',none:'なし'}[config.settings.firstSeer]}。</li><li>騎士は自分を守れません。連続護衛は${config.settings.repeatGuard?'可能':'不可'}。</li><li>同票は候補だけで再投票。再同票なら${config.settings.tie==='none'?'追放なし':'候補から抽選'}。</li><li>脱落時の役職：${{none:'非公開',exile:'追放者のみ公開',all:'全員公開'}[config.settings.reveal]}。投票先：${config.settings.showVotes?'公開':'非公開'}。</li><li>人狼は、仲間の入力済みの襲撃先を見られます。後の順番の人ほど多くの情報を見られます。</li><li>人狼の票が割れたら最多票、同票なら抽選で襲撃先が決まります。</li><li>夜は1周だけ。占い・霊媒の結果はその場で確認し、襲撃は全員の入力後に処理します。</li><li>同じ夜に襲撃される占い師・霊媒師も、朝の脱落発表までは結果を確認できます。</li></ul><div class="notice">秘密の画面は本人だけで確認。操作中はほかの人の画面を見ず、画面を見せて役職を証明しないでください。</div><div class="actions">${btn('start','役職を配る','primary')}${btn('setup','設定に戻る')}</div></section>`;}
function handoff(){let p=current(),phase=game.phase,caption={deal:'役職の確認',night:game.initial?'初日の夜':'夜の行動',results:'夜の確認',vote:game.round?'再投票':'投票'}[phase];app.innerHTML=`<section class="private"><p class="eyebrow">${caption} · ${game.i+1} / ${phase==='deal'?game.players.length:game.queue.length}</p><div class="panel"><div class="private-icon" aria-hidden="true">⌑</div><h1>${esc(p.name)} さんに<br>渡してください</h1><p class="lead" style="margin:0 auto">席番号 ${p.id+1}。まわりから画面が見えない状態で開いてください。</p><div class="actions" style="justify-content:center"><button class="primary hold" id="open-secret">長押しして開く</button></div><p class="hint">約0.7秒長押し。キーボードではEnterを押してください。</p></div>${btn('suspend','隠したまま中断する','subtle')}</section>`;}
function teammates(p){if(p.role==='wolf'||p.role==='fanatic')return game.players.filter(t=>t.role==='wolf'&&t.id!==p.id).map(t=>`${esc(t.name)}（席${t.id+1}）`).join('、')||'ほかの人狼はいません';if(p.role==='shared')return game.players.filter(t=>t.role==='shared'&&t.id!==p.id).map(t=>`${esc(t.name)}（席${t.id+1}）`).join('、');return '';}
function secret(){let p=current(),r=R[p.role],phase=game.phase,content='',can=true,label='確認した・隠して次へ';
 if(phase==='deal'){content=`<div class="role-card-art">${roleArt(p.role)}</div><h1 class="role-title">${r.name}</h1><p class="secret-label">${r.team==='wolf'?'人狼陣営':'村人陣営'}${r.special?' · 特殊役職':''}</p><p class="lead" style="margin:auto">${r.desc}</p><p>${r.team==='wolf'?'人狼陣営':'村人陣営'}が勝てば、脱落してもあなたの勝利です。</p>${teammates(p)?`<div class="notice">${p.role==='shared'?'あなたの相方':'人狼の仲間'}：${teammates(p)}</div>`:''}`;}
 if(phase==='night'){
  if(p.role==='medium'&&!Object.hasOwn(game.actions,p.id)){E.submitNight(game,p.id,null);store();}
  if(p.role==='seer'&&game.initial&&game.settings.firstSeer==='random'&&!Object.hasOwn(game.actions,p.id)){E.submitNight(game,p.id,null);store();}
  let committed=Object.hasOwn(game.actions,p.id);
  let active=!game.initial&&['wolf','seer','knight'].includes(p.role)||game.initial&&p.role==='seer'&&game.settings.firstSeer==='free';
  content=`<h1>${game.initial?'初日の夜':`${game.day}日目の夜`}</h1><p class="secret-label">あなたは ${r.name}</p>`;
  if(p.role==='wolf')content+=`<div class="notice">仲間：${teammates(p)}</div>`;
  if(p.role==='wolf'&&!game.initial){let others=game.players.filter(t=>t.alive&&t.role==='wolf'&&t.id!==p.id);content+=`<h3>仲間の襲撃先</h3><p class="hint">この時点で入力済みの内容です。</p><div class="log">${others.map(t=>`${esc(t.name)} → ${Object.hasOwn(game.actions,t.id)?esc(game.players[game.actions[t.id]]?.name||'対象なし'):'未入力'}`).join('<br>')||'あなた1人で襲撃先を選びます。'}</div>`;}
  if(committed&&game.results[p.id]){content+=`<div class="reading"><span class="eyebrow">${p.role==='seer'?'占い':'霊媒'}の結果</span>${roleArt(p.role)}<h2>${esc(game.results[p.id])}</h2><p class="hint">あなたにだけ分かる情報です。結果を覚えてから画面を隠してください。</p></div>`;label='結果を確認・隠して次へ';}
  else if(active&&!committed){let targets=E.validTargets(game,p.id);content+=`<p>${{wolf:'襲撃したい人',seer:'占いたい人',knight:'守りたい人'}[p.role]}を1人選んでください。</p>${targetButtons(targets)}`;can=targets.length===0||selected!==null;label=targets.length?(p.role==='seer'?'この人を占って結果を見る':'選択を確定・隠して次へ'):'対象なし・隠して次へ';if(!targets.length)content+='<p class="hint">選べる対象がいないため、今夜の能力は使いません。</p>';}
  else content+=`<div class="notice">${game.initial?'初日は襲撃なし。':'今夜、選ぶ行動はありません。'}${game.initial&&p.role==='seer'&&game.settings.firstSeer==='random'?'占いの結果は、この後の確認でお知らせします。':'静かに確認して、次の人に渡してください。'}</div>`;
  if(p.history.length)content+=`<details><summary>自分の過去の結果</summary>${renderHistory(p)}</details>`;
 }
 if(phase==='results'){content=`<h1>今夜の確認</h1><div class="notice">${game.results[p.id]?esc(game.results[p.id]):'今夜、あなたへの新しいお知らせはありません。'}</div>`;if(p.role==='wolf'&&!game.initial&&!game.pendingDead.includes(p.id)){let event=game.events[game.events.length-1];content+=`<h3>人狼みんなの入力</h3><div class="log">${game.players.filter(t=>t.alive&&t.role==='wolf').map(t=>`${esc(t.name)} → ${esc(game.players[game.actions[t.id]]?.name||'対象なし')}`).join('<br>')}</div><p>決まった襲撃先：${esc(game.players[event.attack]?.name||'対象なし')}${event.tied.length>1?'（同票のため抽選）':''}</p><p class="hint">襲撃が成功したかは、朝の発表で確認します。</p>`;}content+='<p class="hint">確認したら画面を隠し、次の人に渡してください。</p>';}
 if(phase==='vote'){content=`<h1>${game.round?'同票候補に再投票':'追放する人を選ぶ'}</h1><p class="hint">自分以外の1人に投票します。全員の投票が終わるまで票は公開されません。</p>${targetButtons(game.candidates.filter(id=>id!==p.id))}`;can=selected!==null;label='投票を確定・隠して次へ';}
 app.innerHTML=`<section class="private"><p class="secret-label">${esc(p.name)} さんだけの画面 · 席${p.id+1}</p><div class="panel">${content}<div class="actions" style="justify-content:center">${btn('secret-next',label,'primary',!can)}${btn('hide','画面を隠す')}</div></div></section>`;armPrivacy();
}
function renderHistory(p){return `<div class="log">${p.history.map(h=>`${h.night===0?'初日':h.night+'日目の夜'}：${esc(h.text)}`).join('<br>')}</div>`;}
function targetButtons(ids){let action=game.phase==='vote'?'投票する人':{wolf:'襲撃する人',seer:'占う人',knight:'護衛する人'}[current().role]||'対象';return `<div class="targets">${ids.map(id=>`<button data-pick="${id}" class="${selected===id?'selected':''}" aria-pressed="${selected===id}"><span class="seat-medallion" aria-hidden="true">${id+1}</span>${esc(game.players[id].name)}<small>席番号 ${id+1}</small></button>`).join('')}</div><p class="target-confirmation" aria-live="polite">${selected===null?'対象を選ぶと、ここで確認できます。':`${action}：<strong>${esc(game.players[selected].name)}（席番号 ${selected+1}）</strong>`}</p>`;}
function progress(phase){return `<div class="phase-track" aria-label="ゲームの進行">${[['morning','朝の発表'],['day','話し合い'],['vote','投票'],['night','夜の行動']].map(([k,t])=>`<span ${k===phase?'class="active" aria-current="step"':''}>${t}</span>`).join('')}</div>`;}
function gather(){let morning=game.phase==='morning';app.innerHTML=`${progress(morning?'morning':'vote')}<section class="private"><p class="eyebrow">${morning?'夜が明けました':'すべての票が集まりました'}</p><div class="panel"><div class="private-icon" aria-hidden="true">${morning?'☀':'✉'}</div><h1>みんなで集まってください</h1><p class="lead" style="margin:auto">端末を机の中央に置き、全員が見られる状態で進めます。<br>${morning?'村の朝のお知らせを発表します。':'投票を締め切りました。これから村の決定を発表します。'}</p><div class="actions" style="justify-content:center">${btn('public',morning?'朝のお知らせを開く':'投票結果を開く','primary')}</div><p class="hint">全員の準備ができてから押してください。</p></div></section>`;}
function revealIntro(){clearTimeout(revealTimer);revealing=true;let morning=game.phase==='morning';app.innerHTML=`${progress(morning?'morning':'vote')}<section class="announcement ${morning?'sunrise':'ballot'}"><div class="reveal-orbit" aria-hidden="true"><span>${morning?'☀':'✉'}</span></div><p class="eyebrow">${morning?'DAWN IN THE VILLAGE':'THE VILLAGE HAS DECIDED'}</p><h1>${morning?'長い夜が、明けてゆきます。':'村の決定を、告げます。'}</h1><p class="lead">${morning?'朝の光が、村を照らし始めました。<br>昨夜、この村では何が起きたのでしょうか。':'一人ひとりの思いが、一つの決定に。<br>静かに、発表をお待ちください。'}</p>${btn('skip-reveal','すぐに結果を見る','subtle')}</section>`;revealTimer=setTimeout(finishReveal,window.matchMedia('(prefers-reduced-motion: reduce)').matches?1200:2600);}
function finishReveal(){clearTimeout(revealTimer);if(!revealing||!game)return;revealing=false;publicOpened=true;render();PublicAudio.play('reveal');}
function roleIfAllowed(p,exile){return game.settings.reveal==='all'||exile&&game.settings.reveal==='exile'?`（${R[p.role].name}）`:'';}
function publicScreen(){let phase=game.phase,title='',body='',next='',story='',guide='',tone='';
 if(phase==='morning'){title=game.initial?'1日目の朝':`${game.day}日目の朝`;body=game.initial?'初日は襲撃なし。全員で話し合いを始めましょう。':game.pendingDead.length?`${game.pendingDead.map(id=>esc(game.players[id].name)+roleIfAllowed(game.players[id],false)).join('、')} さんが脱落しました。`:'昨夜の脱落者はいませんでした。';next=game.winner?'end':'day';}
 if(phase==='tie'){title='最多票が同じでした';body=`${game.candidates.map(id=>esc(game.players[id].name)).join('、')} さんに再投票します。`;next='revote';}
 if(phase==='exile'){title=`${game.day}日目の投票結果`;body=game.lastExile===null?'同票のため、今日は追放なしです。':`${esc(game.players[game.lastExile].name)} さんを追放します${roleIfAllowed(game.players[game.lastExile],true)}。`;next=game.winner?'end':'night';}
 if(phase==='morning'){
  tone=game.pendingDead.length?'loss':'peace';
  story=game.initial?'まだ誰も失われていない、最初の朝。けれど、この村には人狼がひそんでいます。':game.pendingDead.length?'朝の光の中、村に悲しい知らせが届きました。昨夜、一人の仲間が失われました。':'静かな朝を迎えました。昨夜、村から失われた人はいません。';
  guide=game.pendingDead.length?'脱落した方は、ここから発言・投票・夜の行動をせず、村の行方を見守ってください。':'このまま生存者全員で話し合います。';
  if(!game.initial&&!game.pendingDead.length)guide+=' 脱落者がいなかった理由や、騎士の護衛先は公開しません。';
 }
 if(phase==='tie'){tone='tie';story='村の意見は、二つ以上に分かれました。まだ、追放する人は決まっていません。';guide='生存者全員で、表示された同票候補の中から再投票します。候補者も自分以外の候補に投票してください。';}
 if(phase==='exile'){tone=game.lastExile===null?'peace':'loss';story=game.lastExile===null?'再び票が並び、村は今日、誰も追放しないことを選びました。':'票を数え終えました。村が選んだのは、この人です。';guide=game.lastExile===null?'全員が生存したまま、次の夜へ進みます。':'追放された方は、ここから発言・投票・夜の行動をせず、村の行方を見守ってください。';let event=game.events[game.events.length-1];if(event?.type==='exile'&&event.tied.length>1&&event.id!==null)story='再投票でも同票だったため、開始前に決めたルールに従い、候補から抽選しました。';}
 if(game.winner)guide+=' この結果で決着がつきました。全員で「勝敗を見る」を押してください。';else if(phase==='morning')guide+=' まずは昨夜までの情報と、それぞれの考えを話しましょう。';else if(phase==='exile')guide+=' 次の夜は生存者だけが、席順に端末を回して行動します。';
 app.innerHTML=`${progress(phase==='morning'?'morning':'vote')}<p class="eyebrow">村からのお知らせ</p><h1>${title}</h1><section class="panel center announcement-result ${tone}" aria-live="polite"><div class="announcement-symbol" aria-hidden="true">${phase==='morning'?'☀':phase==='tie'?'⚖':'✉'}</div><p class="gm-story">${story}</p><h2 class="verdict">${body}</h2><p class="gm-guide">${guide}</p>${phase!=='morning'?voteTable():''}<div class="actions" style="justify-content:center">${btn(next,{end:'勝敗を見る',day:'話し合いを始める',revote:'再投票する',night:'夜へ進む'}[next],'primary')}</div>${btn('repeat-announcement','発表の文言をもう一度読む','subtle')}</section>`;
}
function voteTable(){return `<div class="scroll"><table><thead><tr><th>候補者</th><th>得票</th></tr></thead><tbody>${Object.entries(game.voteSummary).map(([id,n])=>`<tr><td>${esc(game.players[id].name)}</td><td>${n}票</td></tr>`).join('')}</tbody></table></div>${game.settings.showVotes?`<details><summary>全員の投票先</summary><div class="log">${Object.entries(game.votes).map(([id,to])=>`${esc(game.players[id].name)} → ${esc(game.players[to].name)}`).join('<br>')}</div></details>`:''}`;}
function dayScreen(){let living=E.ids(game);app.innerHTML=`${progress("day")}<div class="topline"><p class="eyebrow">${game.day}日目 · 昼の話し合い</p><span class="count">生存 ${living.length}人 / ${game.players.length}人</span></div><h1>誰を信じる？</h1><div class="split"><section class="panel center"><p class="hint">それぞれの推理を話してみよう。</p><div class="timer" id="timer"></div><p id="timer-cue" class="timer-cue" aria-live="polite"></p><div class="actions" style="justify-content:center">${game.settings.minutes?btn('pause',game.deadline?'一時停止':'タイマーを再開'):''}${game.settings.minutes?btn('extend','＋1分'):''}</div>${btn('vote','話し合いを終えて投票へ','primary wide')}<p class="hint">時間が来ても自動で投票に進みません。</p></section><section class="panel"><h2>村の参加者</h2><div class="players">${game.players.map(p=>`<span class="player ${p.alive?'':'dead'}">${esc(p.name)}${p.alive?'':roleIfAllowed(p,game.events.some(e=>e.type==='exile'&&e.id===p.id))}</span>`).join('')}</div><details><summary>これまでの公開情報</summary><div class="log">${publicLog()}</div></details><p class="hint">脱落した人は、会話に参加せずに見守ってください。</p><div class="actions">${btn('rules','ルールを確認','subtle')}${btn('suspend','中断する','subtle')}</div></section></div>`;updateTimer();}
function publicLog(){return game.events.filter(e=>e.type==='night'||e.type==='exile').map(e=>e.type==='exile'?`${e.day}日目：${e.id===null?'追放なし':esc(game.players[e.id].name)+'を追放'}`:e.night===0?'初日：襲撃なし':`${e.night}日目の夜：${e.dead.length?e.dead.map(id=>esc(game.players[id].name)).join('、')+'が脱落':'脱落者なし'}`).join('<br>');}
function updateTimer(){let el=document.getElementById('timer');if(!el||!game)return;let ms=game.deadline?Math.max(0,game.deadline-Date.now()):game.remaining,cue=document.getElementById('timer-cue');if(!game.settings.minutes){el.textContent='時間制限なし';el.style.fontSize='32px';return;}let s=Math.ceil(ms/1000);el.textContent=`${Math.floor(s/60).toString().padStart(2,'0')}:${(s%60).toString().padStart(2,'0')}`;let text=ms<=0?'話し合いの時間が終了しました。最後の意見をまとめて、投票へ進んでください。':!game.deadline?'タイマーを一時停止しています。全員の準備ができたら再開してください。':s<=30?'残り30秒以内です。まだ話せていない人の意見も聞いてみましょう。':'';if(cue&&cue.textContent!==text)cue.textContent=text;el.classList.toggle('time-up',ms<=0);if(ms<=0)el.setAttribute('aria-label','話し合いの時間が終了しました');else el.removeAttribute('aria-label');if(ms<=0&&game.deadline&&!game.timerFinished&&!document.hidden){game.timerFinished=true;store();PublicAudio.play('timer');}}
function endScreen(){app.innerHTML=`<p class="eyebrow">村の物語、おしまい</p><h1>${game.winner==='village'?'村人陣営':'人狼陣営'}の勝利</h1><p class="lead">${game.winner==='village'?'すべての人狼が追放されました。':'生存している人狼が、それ以外の人と同数以上になりました。'}<br>脱落した人も、所属陣営が勝っていれば勝利です。</p><section class="panel"><h2>みんなの役職</h2><div class="scroll"><table><thead><tr><th>参加者</th><th>役職</th><th>陣営</th><th>結果</th></tr></thead><tbody>${game.players.map(p=>`<tr><td>${esc(p.name)}</td><td>${R[p.role].name}${R[p.role].special?' · 特殊':''}</td><td>${R[p.role].team==='village'?'村人':'人狼'}</td><td>${R[p.role].team===game.winner?'勝利':'敗北'}</td></tr>`).join('')}</tbody></table></div><details><summary>昼と夜を振り返る（秘密情報も公開）</summary><div class="log">${game.events.map(e=>e.type==='night'?`${e.night===0?'初日':e.night+'日目の夜'}：${e.attack===null?'襲撃なし':'襲撃先 '+esc(game.players[e.attack].name)}${e.tied.length>1?'（同票から抽選）':''}<br>${Object.entries(e.actions).filter(([id,to])=>to!==null).map(([id,to])=>`　${esc(game.players[id].name)}［${R[game.players[id].role].name}］→ ${esc(game.players[to].name)}`).join('<br>')}`:e.type==='vote'?`${e.day}日目 ${e.round?'再投票':'投票'}：<br>${Object.entries(e.votes).map(([id,to])=>`　${esc(game.players[id].name)} → ${esc(game.players[to].name)}`).join('<br>')}`:`${e.day}日目：${e.id===null?'追放なし':esc(game.players[e.id].name)+'を追放'}${e.tied.length>1&&e.id!==null?'（同票から抽選）':''}`).join('<hr>')}</div></details><div class="actions">${btn('again','同じ設定でもう一度','primary')}${btn('setup','設定を変えて遊ぶ')}${btn('home','ホーム')}</div></section>`;}
function render(){clearInterval(timerLoop);if(screen==='home')home();else if(screen==='setup')setup();else if(screen==='confirm')confirmScreen();else if(game){if(['deal','night','results','vote'].includes(game.phase)){PublicAudio.stop();if(opened)secret();else handoff();}else if(['morning','tie','exile'].includes(game.phase)){if(publicOpened)publicScreen();else gather();}else if(game.phase==='day'){dayScreen();timerLoop=setInterval(updateTimer,500);}else if(game.phase==='end')endScreen();}if(screen!=='game'||game&&['morning','tie','exile','day','end'].includes(game.phase))app.insertAdjacentHTML('beforeend',audioControls());if(saveError)app.insertAdjacentHTML('afterbegin',`<p class="save-status" role="alert">${saveError}</p>`);}
function armPrivacy(){clearTimeout(inactivity);inactivity=setTimeout(()=>{if(opened){opened=false;selected=null;render();}},30000);}
function newGame(){let error=E.validate(config.counts,config.n);if(error)return dialog('設定を確認',esc(error));game=E.create(config.names,config.counts,config.settings);screen='game';go();}
function dialog(title,html){document.querySelector('dialog')?.remove();let d=document.createElement('dialog');d.innerHTML=`<h2>${title}</h2>${html}<div class="actions">${btn('close-dialog','閉じる')}</div>`;document.body.append(d);d.showModal();}
function rules(){dialog('遊び方',`<div class="log"><p>役職を確認 → 初日の夜（自分で占う・襲撃なし） → 話し合い → 秘密投票 → 夜の行動 → 朝の発表、の順に進みます。</p><p>夜は1周だけ。占い・霊媒の結果は自分の手番で確認します。村人にも確認画面があるので、役職は順番から分かりません。</p><p>村人陣営は人狼全滅、人狼陣営は人狼とそれ以外の生存者が同数以上になれば勝利。狂人・狂信者は人狼の味方ですが、人狼の人数には入りません。</p><p>人狼は入力済みの仲間の襲撃先を見られます。最多票で襲撃先を決め、同票は抽選します。</p><p>配役や投票結果の秘密画面は見せず、脱落後は話し合いに参加しないでください。</p></div>`);}
document.addEventListener('click',e=>{
 let pick=e.target.closest('[data-pick]');if(pick&&opened){selected=Number(pick.dataset.pick);secret();return;}
 let b=e.target.closest('[data-action]');if(!b||b.disabled)return;let a=b.dataset.action;
 if(a==='close-dialog'){b.closest('dialog').remove();return;}
 if(a==='toggle-audio'){PublicAudio.toggle();render();if(game?.phase==='day'&&PublicAudio.enabled)PublicAudio.prepare();return;}
 if(a==='rules'){rules();return;}
 if(a==='home'){if(game&&game.phase!=='end')store();resetPrivate();screen='home';render();return;}
 if(a==='setup'){screen='setup';resetPrivate();render();return;}
 if(a.startsWith('plus:')||a.startsWith('minus:')){let [op,k]=a.split(':');config.counts[k]+=op==='plus'?1:-1;config.kind='custom';setup();return;}
 if(a==='fill'){let other=Object.entries(config.counts).filter(([k])=>k!=='villager').reduce((s,[k,v])=>s+v,0);config.counts.villager=Math.max(0,config.n-other);config.kind='custom';setup();return;}
 if(a==='confirm'){if(E.validate(config.counts,config.n))return;screen='confirm';render();window.scrollTo(0,0);return;}
 if(a==='start'){if(getSaved())dialog('途中のゲームがあります',`<p>新しく始めると、保存されている途中のゲームを削除します。</p>${btn('replace-start','削除して新しく始める','primary')}`);else newGame();return;}
 if(a==='replace-start'){b.closest('dialog').remove();newGame();return;}
 if(a==='resume'){let g=getSaved();if(!goodGame(g))return dialog('再開できません','<p>保存データの形式が確認できません。新しいゲームを始めてください。</p>');game=g;if(game.phase==='results')E.dawn(game);screen='game';go();return;}
 if(a==='save-preset'){if(E.validate(config.counts,config.n))return dialog('設定を確認','<p>人数と配役を合わせてから保存してください。</p>');dialog('設定に名前をつける',`<label>名前<input id="preset-name" type="text" maxlength="30" value="${config.n}人の村"></label>${btn('store-preset','保存','primary')}`);return;}
 if(a==='store-preset'){let name=document.getElementById('preset-name').value.trim()||'マイ設定';try{let presets=savedPresets();presets.push({name,config:JSON.parse(JSON.stringify(config))});localStorage.setItem(PRESETS,JSON.stringify(presets.slice(-20)));b.closest('dialog').remove();}catch{dialog('保存できません','<p>ブラウザの保存設定を確認してください。</p>');}return;}
 if(a==='load-preset'){let list=savedPresets();dialog('保存した設定',list.length?list.map((p,i)=>`<div class="actions">${btn('preset:'+i,esc(p.name)+' · '+p.config.n+'人')}${btn('delete-preset:'+i,'削除','subtle')}</div>`).join(''):'<p>まだ保存した設定はありません。</p>');return;}
 if(a.startsWith('preset:')){let p=savedPresets()[Number(a.split(':')[1])];if(p&&p.config&& !E.validate(p.config.counts,p.config.n)){config=p.config;b.closest('dialog').remove();setup();}return;}
 if(a.startsWith('delete-preset:')){try{let list=savedPresets();list.splice(Number(a.split(':')[1]),1);localStorage.setItem(PRESETS,JSON.stringify(list));b.closest('dialog').remove();}catch{dialog('削除できません','<p>保存設定を確認してください。</p>');}return;}
 if(a==='hide'){opened=false;selected=null;clearTimeout(inactivity);render();return;}
 if(a==='suspend'){if(game.phase==='day'&&game.deadline){game.remaining=Math.max(0,game.deadline-Date.now());game.deadline=null;}store();resetPrivate();screen='home';render();return;}
 if(a==='secret-next'){
  let p=current();if(game.phase==='night'){let fresh=!Object.hasOwn(game.actions,p.id);E.submitNight(game,p.id,selected);if(fresh&&p.role==='seer'&&game.results[p.id]){selected=null;store();secret();return;}}if(game.phase==='vote')E.submitVote(game,p.id,selected);
  game.i++;
  if(game.phase==='deal'&&game.i>=game.players.length)E.startNight(game,true);
  else if(game.phase==='night'&&game.i>=game.queue.length)E.resolveNight(game);
  else if(game.phase==='results'&&game.i>=game.queue.length)E.dawn(game);
  else if(game.phase==='vote'&&game.i>=game.queue.length)E.resolveVote(game);
  go();return;
 }
 if(a==='public'){revealIntro();PublicAudio.play(game.phase==='morning'?'dawn':'ballot');return;}
 if(a==='skip-reveal'){finishReveal();return;}
 if(a==='repeat-announcement'){let text=app.querySelector('.gm-story').textContent+'\n\n'+app.querySelector('.verdict').textContent+'\n\n'+app.querySelector('.gm-guide').textContent;dialog('村からのお知らせ',`<p class="log">${esc(text).replace(/\n/g,'<br>')}</p>`);return;}
 if(a==='day'){game.phase='day';game.timerFinished=false;if(game.settings.minutes)game.deadline=Date.now()+game.remaining;go();PublicAudio.prepare();return;}
 if(a==='pause'){if(game.deadline){game.remaining=Math.max(0,game.deadline-Date.now());game.deadline=null;}else game.deadline=Date.now()+game.remaining;store();render();return;}
 if(a==='extend'){if(game.deadline)game.deadline=Math.max(game.deadline,Date.now())+60000;else game.remaining+=60000;game.timerFinished=false;store();render();return;}
 if(a==='vote'){dialog('話し合いを終えて投票しますか？','<p class="log">生存者全員が、自分以外の1人を選びます。投票を始めると、この話し合いには戻れません。</p>'+btn('begin-vote','全員の準備ができた・投票へ','primary'));return;}
 if(a==='begin-vote'){b.closest('dialog').remove();E.startVote(game);go();return;}
 if(a==='revote'){E.revote(game);go();return;}
 if(a==='night'){E.startNight(game);go();return;}
 if(a==='end'){game.phase='end';go();PublicAudio.play('victory');return;}
 if(a==='again'){config={n:game.players.length,names:game.players.map(p=>p.name),counts:{...game.counts},kind:'custom',settings:{...game.settings}};newGame();return;}
});
document.addEventListener('input',e=>{if(e.target.matches('[data-name]'))config.names[Number(e.target.dataset.name)]=e.target.value;if(e.target.matches('[data-volume]'))PublicAudio.setVolume(Number(e.target.value)/100);if(opened)armPrivacy();});
document.addEventListener('change',e=>{
 let el=e.target;if(el.id==='number'){let n=Number(el.value);config.names=Array.from({length:n},(_,i)=>config.names[i]||`参加者${i+1}`);config.n=n;config.counts=E.preset(n,config.kind==='custom'?'basic':config.kind);if(config.kind==='custom')config.kind='basic';setup();}
 if(el.id==='kind'){config.kind=el.value;if(el.value!=='custom')config.counts=E.preset(config.n,el.value);setup();}
 if(el.dataset.setting){let k=el.dataset.setting,v=el.value;config.settings[k]=['repeatGuard','showVotes'].includes(k)?v==='true':k==='minutes'?Number(v):v;}
});
function openSecret(){if(screen!=='game'||!game||!['deal','night','results','vote'].includes(game.phase))return;PublicAudio.stop();opened=true;selected=null;secret();}
document.addEventListener('pointerdown',e=>{let el=e.target.closest('#open-secret');if(!el)return;el.setPointerCapture(e.pointerId);el.classList.add('holding');holdTimer=setTimeout(openSecret,700);});
for(let event of ['pointerup','pointercancel'])document.addEventListener(event,()=>{clearTimeout(holdTimer);document.getElementById('open-secret')?.classList.remove('holding');});
document.addEventListener('keydown',e=>{if(e.target.id==='open-secret'&&(e.key==='Enter'||e.key===' ')){e.preventDefault();openSecret();}if(opened)armPrivacy();});
document.addEventListener('pointerdown',()=>{if(opened)armPrivacy();});
function conceal(){PublicAudio.stop();clearTimeout(holdTimer);if(opened){opened=false;selected=null;clearTimeout(inactivity);render();}}
document.addEventListener('visibilitychange',()=>{if(document.hidden)conceal();});window.addEventListener('blur',conceal);window.addEventListener('pagehide',()=>{conceal();if(game)store();});
window.history.pushState(null,'');window.addEventListener('popstate',()=>{conceal();window.history.pushState(null,'');});
render();

document.querySelector('.ambient').innerHTML=villageArt();
